version: '3'
services:
  authors:
    image: estoyanov/bff-authors-service:1.0
    container_name: bff-authors-service
    ports:
        - 8080:8080
    networks:
        - mynet
  books:
    image: estoyanov/bff-books-service:1.0
    container_name: bff-books-service
    ports:
        - 8081:8080
    networks:
        - mynet    
  web-sockets:
    image: estoyanov/bff-web-sockets-service:1.0
    container_name: bff-web-sockets-service
    ports:
       - 8082:8080
    networks:
        - mynet           
networks:
  mynet: